package com.ottocabellom.mortgage;

import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity {
  int navy=Color.rgb(11,25,44), dark=Color.rgb(6,16,30), accent=Color.rgb(37,99,235), white=Color.WHITE, slate=Color.rgb(148,163,184), green=Color.rgb(16,185,129), red=Color.rgb(244,63,94);
  EditText amount, rate, years, recur; boolean french=true; int tab=1; double[] extras1=new double[41], extras2=new double[41]; LinearLayout root, results, tableBox; TextView payment, baseInt, baseTotal, s1Int,s1Save,s1Last,s2Int,s2Save,s2Time; TableLayout table;
  DecimalFormat money=new DecimalFormat("$#,##0.00");
  @Override public void onCreate(Bundle b){super.onCreate(b); build(); recalc();}
  TextView tv(String s,int sp,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(color);t.setPadding(0,4,0,4);return t;}
  GradientDrawable bg(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(r);return g;}
  EditText input(String label,String val){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);TextView l=tv(label,12,Color.LTGRAY);l.setPadding(0,0,0,5);box.addView(l);EditText e=new EditText(this);e.setText(val);e.setTextColor(white);e.setTextSize(15);e.setSingleLine();e.setInputType(2|8192);e.setPadding(14,8,14,8);e.setBackground(bg(Color.rgb(15,30,50),18));box.addView(e);results.addView(box,new LinearLayout.LayoutParams(-1,-2));return e;}
  Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextColor(white);b.setTextSize(12);b.setAllCaps(false);b.setBackground(bg(accent,18));return b;}
  void cardTitle(LinearLayout c,String s){TextView t=tv(s,16,white);t.setTypeface(null,1);c.addView(t);}
  LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(18,16,18,16);c.setBackground(bg(navy,26));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,14);root.addView(c,p);return c;}
  void build(){
    ScrollView sv=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(18,18,18,28);root.setBackgroundColor(dark);sv.addView(root);setContentView(sv);
    LinearLayout head=card(); TextView h=tv("🏦  OTTOCABELLOM",24,white);h.setTypeface(null,1);head.addView(h);head.addView(tv("SIMULADOR DE AMORTIZACIÓN HIPOTECARIA",11,Color.rgb(147,197,253)));
    LinearLayout sys=new LinearLayout(this);sys.setPadding(0,12,0,0);Button bf=btn("Francés · Cuota fija"), bg=btn("Alemán · Capital fijo");sys.addView(bf,new LinearLayout.LayoutParams(0,52,1));LinearLayout.LayoutParams gp=new LinearLayout.LayoutParams(0,52,1);gp.setMargins(8,0,0,0);sys.addView(bg,gp);head.addView(sys);bf.setOnClickListener(v->{french=true;bf.setBackground(bg(accent,18));bg.setBackground(bg(Color.rgb(35,50,70),18));recalc();});bg.setOnClickListener(v->{french=false;bg.setBackground(bg(accent,18));bf.setBackground(bg(Color.rgb(35,50,70),18));recalc();});
    LinearLayout params=card();cardTitle(params,"⚙ Parámetros base");results=params;amount=input("Monto del préstamo ($)","100000");rate=input("Tasa EAP anual (%)","6.0");years=input("Plazo (años)","20");
    TextView ar=tv("⚡ ABONO RECURRENTE ANUAL",12,Color.rgb(147,197,253));ar.setPadding(0,16,0,5);params.addView(ar);recur=input("Abono anual extra a capital ($)","1000");Button apply=btn("Aplicar a todos los años");params.addView(apply);apply.setOnClickListener(v->{double x=num(recur);for(int i=1;i<41;i++){extras1[i]=x;extras2[i]=x;}recalc();});Button reset=btn("↻  Resetear abonos");reset.setBackground(bg(Color.rgb(35,50,70),18));params.addView(reset);reset.setOnClickListener(v->{Arrays.fill(extras1,0);Arrays.fill(extras2,0);recur.setText("0");recalc();});
    LinearLayout base=card();cardTitle(base,"Resumen original");payment=metric(base,"Cuota inicial: ");baseInt=metric(base,"Intereses sin abonos: ");baseTotal=metric(base,"Total original: ");
    LinearLayout sc=card();cardTitle(sc,"📊 Comparación de estrategias");s1Int=metric(sc,"Escenario 1 · Intereses: ");s1Save=metric(sc,"Ahorro intereses: ");s1Last=metric(sc,"Última cuota: ");s2Int=metric(sc,"Escenario 2 · Intereses: ");s2Save=metric(sc,"Ahorro intereses: ");s2Time=metric(sc,"Plazo final: ");
    TextView tabs=tv("ESCENARIO 1: REDUCIR CUOTA / LETRA     |     ESCENARIO 2: REDUCIR TIEMPO",12,white);tabs.setGravity(Gravity.CENTER);tabs.setPadding(8,16,8,16);tabs.setBackground(bg(accent,18));root.addView(tabs);tabs.setOnClickListener(v->{tab=tab==1?2:1;recalc();});
    tableBox=card();cardTitle(tableBox,"Tabla de amortización");table=new TableLayout(this);table.setStretchAllColumns(false);tableBox.addView(table);root.addView(tv("Los cálculos siguen la lógica del simulador HTML original. Los abonos se aplican al capital al cierre de cada año.",11,slate));
    View.OnFocusChangeListener f=(v,has)->{if(!has)recalc();}; amount.setOnFocusChangeListener(f);rate.setOnFocusChangeListener(f);years.setOnFocusChangeListener(f);
  }
  TextView metric(LinearLayout c,String label){TextView t=tv(label+"$0.00",14,white);t.setPadding(0,8,0,8);c.addView(t);return t;}
  double num(EditText e){try{return Double.parseDouble(e.getText().toString().replace(",",""));}catch(Exception x){return 0;}}
  int nYears(){return Math.max(1,Math.min(40,(int)num(years)));}
  double rateM(){double r=num(rate)/100;return r>0?Math.pow(1+r,1.0/12)-1:0;}
  double basePay(double a,double rm,int months){if(rm==0)return a/months;return a*(rm*Math.pow(1+rm,months))/(Math.pow(1+rm,months)-1);}
  static class Row{int y;double start,pay,cap,intt,extra,end;Row(int y,double s,double p,double c,double i,double e,double en){this.y=y;start=s;pay=p;cap=c;intt=i;extra=e;end=en;}}
  static class Result{ArrayList<Row> rows=new ArrayList<>();double interest,last;int realYears,yearsSaved;}
  Result calc1(){double a=num(amount),rm=rateM();int yrs=nYears();Result r=new Result();double bal=a;for(int y=1;y<=yrs&&bal>.01;y++){double start=bal,yi=0,yc=0;int rem=(yrs-y+1)*12;double mp=french?basePay(bal,rm,rem):0;for(int m=1;m<=12&&bal>.01;m++){double in=bal*rm;double pr=french?mp-in:start/rem;if(pr>bal)pr=bal;bal-=pr;yi+=in;yc+=pr;r.last=pr+in;}double ex=Math.min(extras1[y],Math.max(0,bal));bal-=ex;r.interest+=yi;r.rows.add(new Row(y,start,yi+yc+ex,yc+ex,yi,ex,Math.max(0,bal)));}r.realYears=r.rows.size();return r;}
  Result calc2(){double a=num(amount),rm=rateM();int yrs=nYears(),months=yrs*12;Result r=new Result();double bal=a,mp=french?basePay(a,rm,months):0;for(int y=1;y<=yrs&&bal>.01;y++){double start=bal,yi=0,yc=0;for(int m=1;m<=12&&bal>.01;m++){double in=bal*rm;double pr=french?mp-in:a/months;if(pr>bal)pr=bal;bal-=pr;yi+=in;yc+=pr;}double ex=Math.min(extras2[y],Math.max(0,bal));bal-=ex;r.interest+=yi;r.rows.add(new Row(y,start,yi+yc+ex,yc+ex,yi,ex,Math.max(0,bal)));}r.realYears=r.rows.size();r.yearsSaved=Math.max(0,yrs-r.realYears);return r;}
  double baseInterest(){double a=num(amount),rm=rateM();int months=nYears()*12;double bal=a,interest=0,mp=french?basePay(a,rm,months):0;for(int m=1;m<=months&&bal>.01;m++){double in=bal*rm;double pr=french?mp-in:a/months;if(pr>bal)pr=bal;bal-=pr;interest+=in;}return interest;}
  void recalc(){if(amount==null)return;double a=num(amount),rm=rateM();int months=nYears()*12;double bi=baseInterest();double bp=french?basePay(a,rm,months):a/months+a*rm;payment.setText("Cuota inicial: "+money.format(bp)+" / mes");baseInt.setText("Intereses sin abonos: "+money.format(bi));baseTotal.setText("Total original: "+money.format(a+bi));Result r1=calc1(),r2=calc2();s1Int.setText("Escenario 1 · Intereses: "+money.format(r1.interest));s1Save.setText("Ahorro intereses: "+money.format(Math.max(0,bi-r1.interest)));s1Last.setText("Última cuota: "+money.format(r1.last)+" / mes");s2Int.setText("Escenario 2 · Intereses: "+money.format(r2.interest));s2Save.setText("Ahorro intereses: "+money.format(Math.max(0,bi-r2.interest)));s2Time.setText("Plazo final: "+r2.realYears+" años (ahorra "+r2.yearsSaved+")");render(tab==1?r1:r2);}
  void render(Result r){table.removeAllViews();String[] hs={"Año","Saldo inicial","Cuota anual","Capital","Interés","Abono extra","Saldo final"};TableRow h=new TableRow(this);for(String s:hs){TextView t=tv(s,10,white);t.setTypeface(null,1);t.setPadding(8,10,8,10);t.setBackgroundColor(navy);h.addView(t);}table.addView(h);for(Row x:r.rows){TableRow tr=new TableRow(this);String[] v={""+x.y,money.format(x.start),money.format(x.pay),money.format(x.cap),money.format(x.intt),money.format(x.extra),money.format(x.end)};for(int i=0;i<v.length;i++){ if(i==5){ EditText e=new EditText(this); e.setText(x.extra==0?"":String.format(Locale.US,"%.2f",x.extra)); e.setTextSize(10); e.setTextColor(navy); e.setInputType(2|8192); e.setSingleLine(); e.setPadding(6,5,6,5); e.setSelectAllOnFocus(true); final int yy=x.y; e.setOnFocusChangeListener((vv,has)->{ if(!has){double z=0; try{z=Math.max(0,Double.parseDouble(e.getText().toString()));}catch(Exception ignored){} if(tab==1)extras1[yy]=z;else extras2[yy]=z; recalc(); }}); tr.addView(e); } else {TextView t=tv(v[i],10,Color.DKGRAY);t.setPadding(8,9,8,9);tr.addView(t);} }table.addView(tr);}TableRow f=new TableRow(this);TextView ft=tv("Intereses totales: "+money.format(r.interest),12,Color.DKGRAY);ft.setPadding(8,12,8,12);f.addView(ft);table.addView(f);}
}
